# Generated by Django 5.0.3 on 2024-03-13 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='No se permite ingresar letras, solo números', regex='^\\d+$')])),
            ],
        ),
    ]
